name    'AlexCline-mounts'
version '0.3.0'
author 'Alex Cline <alex.cline@gmail.com>'
license 'Apache License, Version 2.0'
summary 'The mounts module will help manage mount points on linux systems.'
description 'The mounts module will help manage mount points on linux systems.'
project_page 'https://github.com/AlexCline/fstab'
dependency 'AlexCline/fstab', '>= 0.1.0'
dependency 'AlexCline/dirtree', '>= 0.1.1'
